language: android
android:
  components:
    - tools
    - build-tools-29.0.3
    - android-29
    - platform-tools
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'

sudo: required

jdk:
  - oraclejdk8

install: true

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleDebug